[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1.0.163", features=["derive"]}
serde_yaml = "0.9.21"
rocket = "=0.5.1"
reqwest = "0.11.18"
serde_json = "1.0"
# rocket_contrib = "0.4"
lazy_static = "1.4.0"